---

- name: install system nginx
  apt: pkg=nginx-full
  become: true

- name: make sure /etc/nginx/ssl exists
  file: path={{ssl_path}}/ state={{item}} owner=root group=root mode=0700
  become: true
  with_items:
    - directory
    - touch

- name: install SSL key
  copy: src='../../../security/ssl.key' dest={{ssl_key_path}} owner=root group=root mode=0600
  become: true

- name: install SSL certificate
  copy: src='../../../security/ssl.crt' dest={{ssl_cert_path}} owner=root group=root mode=0600
  become: true

- name: install nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644 backup=yes
  become: true
  notify:
    - reload nginx

- name: start the nginx service
  service: name=nginx state=started enabled=yes
  become: true

- name: reload nginx
  service: name=nginx state=reloaded
  become: true
