---
# The playbook deploys JupyterHub.
# This file would be equivalent to a `sites.yml` file in Ansible terms.

- hosts: jupyterhub_hosts
  tasks:
    - assert:
        that: (ansible_version.major, ansible_version.minor) >= (2, 1)
        msg: require ansible >= 2.1, found {{ansible_version.full}}

    - command: echo "$PATH"
      register: default_path


- hosts: jupyterhub_hosts
  tasks:
    - name: Make sure we are running on Ubuntu
      fail: msg="This ansible setup only work on Ubuntu"
      when: ansible_distribution != 'Ubuntu' 


- hosts: jupyterhub_hosts
  roles:
    - common
    - python
    - nginx
    - supervisor
    - saveusers
    - jupyterhub
    - role: cull_idle
      when: use_cull_idle_servers is defined and use_cull_idle_servers
    - role: nbgrader
      when: use_nbgrader is defined and use_nbgrader
    - role: start_jupyterhub
  environment:
      PATH: "/opt/conda/bin:{{ default_path.stdout }}"
