---

- name: install oauthenticator via pip
  pip: name={{item}} state=present executable=pip
  become: true
  with_items:
    - oauthenticator
    - jupyterhub-systemdspawner

- name: install jupyterhub
  conda: name={{item}} state=present
  become: true
  with_items:
    - jupyterhub
