---
# Uses conda to install ipython and jupyter dependencies and python3 kernel

- name: conda install ipython and jupyter deps
  conda: name={{item}} state=present
  become: true
  with_items:
    - notebook
    - ipyparallel
    - ipykernel
    - nbconvert
    - ipywidgets
    - jupyter_contrib_nbextensions

- name: install python3 kernelspec
  command: python3 -m IPython kernel install
  become: true


- name: enabling nbextensions
  command: jupyter nbextension enable {{ item }} --system --sys-prefix
  with_items:
    - exercise2/main
