---

- name: conda install nbgrader
  conda: name={{item}} state=present
  become: true
  with_items:
    - nbgrader

- name: make sure /var/log/nbgrader exists
  file: path={{nbgrader_log_dir}}/ state={{item}} owner=root group=root mode=0755
  become: true
  with_items:
    - directory
    - touch

- name: make sure /srv/nbgrader/exchange exists
  file: path={{nbgrader_exchange_dir}}/ state={{item}} owner=root group=root mode=0733
  become: true
  with_items:
    - directory
    - touch

- name: make sure /srv/nbgrader/exchange/<course> exists
  file: path={{nbgrader_exchange_dir}}/{{item[0].course_id}} state={{item[1]}} owner=root group=root mode=0733
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['directory', 'touch']

- name: create admin group
  group: name=admins

# if deploying to a testing server, set a trivial password for PAM auth
# the password is `This is my Password`
- name: create instructor user accounts (with password)
  user: name={{item}} groups=admins append=yes password={{'pass'|password_hash('sha512')}}
  with_items: '{{jupyterhub_admin_users}}'
  when: inventory_hostname == "testing"

# if deploying to a real server, don't give the admin accounts passwords
# assume they can SSH in with public key auth or just use root
- name: create instructor user accounts (without password)
  user: name={{item}} groups=admins append=yes
  with_items: '{{jupyterhub_admin_users}}'
  when: inventory_hostname != "testing"

# create an account for nbgrader
- name: create nbgrader account
  user: name=nbgrader

# each course lives in /home/nbgrader/courses/<course_id>
- name: make sure courses directory exists
  file: path={{home_dir}}/nbgrader/courses/{{item[0].course_id}}/ state={{item[1]}} owner=nbgrader group=nbgrader mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['directory', 'touch']

- name: make sure subdirectories exist
  file: path={{home_dir}}/nbgrader/courses/{{item[0].course_id}}/{{item[1]}}/ state=directory owner=nbgrader group=nbgrader mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['source', 'release', 'feedback', 'autograded', 'submitted']

- name: install nbgrader config file
  template: src=nbgrader_config.py.j2 dest={{home_dir}}/nbgrader/courses/{{item.course_id}}/nbgrader_config.py owner=nbgrader group=nbgrader mode=700
  become: true
  with_items:
    - "{{nbgrader_courses}}"
